name: Deploy

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - name: Copy to s3 www.willgriffiths.co
        run: aws s3 sync ./ s3://www.willgriffiths.co
      - name: Copy to s3 willgriffiths.co
        run: aws s3 sync ./ s3://willgriffiths.co
      - name: Copy to s3 www.willgriff.co.uk
        run: aws s3 sync ./ s3://www.willgriff.co.uk
      - name: Copy to s3 willgriff.co.uk
        run: aws s3 sync ./ s3://willgriff.co.uk
